### ISSUE TITLE
Linter error for PRs

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-webservices#126]
```
2017-10-03T02:05:34.419264+00:00 app[web.1]: Traceback (most recent call last):
2017-10-03T02:05:34.419265+00:00 app[web.1]:   File "/app/.conda/lib/python3.5/site-packages/tornado/web.py", line 1509, in _execute
2017-10-03T02:05:34.419266+00:00 app[web.1]:     result = method(*self.path_args, **self.path_kwargs)
2017-10-03T02:05:34.419268+00:00 app[web.1]:   File "/app/conda_forge_webservices/webapp.py", line 82, in post
2017-10-03T02:05:34.419270+00:00 app[web.1]:     ref_merge.checkout(force=True)
2017-10-03T02:05:34.419268+00:00 app[web.1]:     repo_name == 'staged-recipes')
2017-10-03T02:05:34.419269+00:00 app[web.1]:   File "/app/conda_forge_webservices/linting.py", line 95, in compute_lint_message
2017-10-03T02:05:34.419270+00:00 app[web.1]: UnboundLocalError: local variable 'ref_merge' referenced before assignment
```

**Comment by jakirkham** [comment]
Right. So we could try sleeping for a little bit after the PR opens and/or retrying at some fixed interval for some number of attempts.
