### ISSUE TITLE
restart command not working

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#273]
The restart command is not working. 

https://github.com/conda-forge/instaseis-feedstock/pull/17

**Comment by beckermr** [comment]
@scopatz Is this related to when the bot was redeployed?

**Comment by scopatz** [comment]
probably not. that should not have effected things

**Comment by beckermr** [comment]
Weird. The rerender command is working and follows the same code path. I don’t understand what’s going.

**Comment by beckermr** [comment]
Is there a way I can access logs from what the bot did with the pr above? This might help debug.

**Comment by scopatz** [comment]
hmm I am not sure how . @isuru?

**Comment by beckermr** [comment]
The test I wrote for this is working, so I think the error is somewhere else. Either the web app never gets to the section of code given then command or there is something going on with the api requests.

**Comment by isuruf** [comment]
```
2019-09-15T16:39:35.161981+00:00 app[web.1]: Traceback (most recent call last):
2019-09-15T16:39:35.161983+00:00 app[web.1]: File "/app/.conda/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
2019-09-15T16:39:35.161986+00:00 app[web.1]: result = method(*self.path_args, **self.path_kwargs)
2019-09-15T16:39:35.161988+00:00 app[web.1]: File "/app/conda_forge_webservices/webapp.py", line 259, in post
2019-09-15T16:39:35.161990+00:00 app[web.1]: commands.pr_comment(owner, repo_name, issue_num, comment)
2019-09-15T16:39:35.161992+00:00 app[web.1]: File "/app/conda_forge_webservices/commands.py", line 31, in pr_comment
2019-09-15T16:39:35.161995+00:00 app[web.1]: pr_detailed_comment(org_name, repo_name, pr.head.user.login, pr.head.repo.name, pr.head.ref, issue_num, comment)
2019-09-15T16:39:35.161997+00:00 app[web.1]: File "/app/conda_forge_webservices/commands.py", line 56, in pr_detailed_comment
2019-09-15T16:39:35.161999+00:00 app[web.1]: pull.edit(state='closed')
2019-09-15T16:39:35.162002+00:00 app[web.1]: File "/app/.conda/lib/python3.7/site-packages/github/PullRequest.py", line 516, in edit
2019-09-15T16:39:35.162004+00:00 app[web.1]: input=post_parameters
2019-09-15T16:39:35.162006+00:00 app[web.1]: File "/app/.conda/lib/python3.7/site-packages/github/Requester.py", line 275, in requestJsonAndCheck
2019-09-15T16:39:35.162008+00:00 app[web.1]: return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
2019-09-15T16:39:35.162010+00:00 app[web.1]: File "/app/.conda/lib/python3.7/site-packages/github/Requester.py", line 286, in __check
2019-09-15T16:39:35.162013+00:00 app[web.1]: raise self.__createException(status, responseHeaders, output)
2019-09-15T16:39:35.162015+00:00 app[web.1]: github.GithubException.GithubException: 422 {'message': 'Validation Failed', 'errors': [], 'documentation_url': 'https://developer.github.com/v3/pulls/#update-a-pull-request'}
```

**Comment by beckermr** [comment]
Ok. So it’s the api requests. Thanks for the logs @isuruf! I’ll fix.

**Comment by beckermr** [comment]
Well the API is being called correctly: https://developer.github.com/v3/pulls/#input-2 and I am using the `github` python package correctly: https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest.edit

Also, the github response is not returning anything in the `errors` field, which is not helpful. See here: https://developer.github.com/v3/#client-errors

Finally, this worked just a week ago. 

I'm wondering if this is an upstream problem with github itself.

**Comment by beckermr** [comment]
OK I tested the API calls I was making with my own repo and they all work fine. @scopatz @isuruf did we change the permissions/scoping on the API key used by the bot recently?

**Comment by isuruf** [comment]
I checked with the `conda-forge-linter`'s token and my personal token. Neither of them work.

**Comment by beckermr** [comment]
That’s very weird. Idk how GitHub handles permissions for stuff like this. On my own repos with my own token, this works fine, so maybe it has to do with conda-forge being an organization? 

Without seeing more about what specific access rights are granted on the linter’s token, it is going to be hard for me to do much more debugging here.

Idk how much more information you all can share on this and I am very sensitive to any security concerns. 

Let me know how you’d like to proceed!

**Comment by beckermr** [comment]
this is working now. :/ closing
