### ISSUE TITLE
Many re-rendering PRs missing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#29]
Alright, it appears there are about 30 feedstocks that still use the old docker image as [quick search]( https://github.com/search?utf8=%E2%9C%93&q=org%3Aconda-forge+pelson%2Fobvious-ci%3Alatest_x64&type=Code&ref=searchresults ) will suggest. This the case even after merging many re-rendering PRs. I raised a couple issues on feedstocks, but it would be good if we could get to the bottom of why this is happening and try to fix it. Do you have any thoughts on this, @pelson?

**Comment by pelson** [comment]
```
2016-06-05T02:03:59.952815+00:00 app[scheduler.4949]: Checking lmfit-feedstock
2016-06-05T02:03:59.954538+00:00 app[scheduler.4949]: Traceback (most recent call last):
2016-06-05T02:03:59.954548+00:00 app[scheduler.4949]:   File "conda-forge.github.io/scripts/lint_feedstocks.py", line 78, in <module>
2016-06-05T02:03:59.954549+00:00 app[scheduler.4949]:     lint = conda_smithy.lint_recipe.main(os.path.join(feedstock.directory, 'recipe'))
2016-06-05T02:03:59.954549+00:00 app[scheduler.4949]:   File "/app/.conda/lib/python3.5/site-packages/conda_smithy/lint_recipe.py", line 140, in main
2016-06-05T02:03:59.954550+00:00 app[scheduler.4949]:     content = env.from_string(''.join(fh)).render()
2016-06-05T02:03:59.954551+00:00 app[scheduler.4949]:   File "/app/.conda/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
2016-06-05T02:03:59.954551+00:00 app[scheduler.4949]:     return self.environment.handle_exception(exc_info, True)
2016-06-05T02:03:59.954552+00:00 app[scheduler.4949]:   File "/app/.conda/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
2016-06-05T02:03:59.954553+00:00 app[scheduler.4949]:     reraise(exc_type, exc_value, tb)
2016-06-05T02:03:59.954553+00:00 app[scheduler.4949]:   File "/app/.conda/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
2016-06-05T02:03:59.954554+00:00 app[scheduler.4949]:     raise value.with_traceback(tb)
2016-06-05T02:03:59.954554+00:00 app[scheduler.4949]:   File "<template>", line 32, in top-level template code
2016-06-05T02:03:59.954554+00:00 app[scheduler.4949]:   File "/app/.conda/lib/python3.5/site-packages/jinja2/environment.py", line 408, in getattr
2016-06-05T02:03:59.954555+00:00 app[scheduler.4949]:     return getattr(obj, attribute)
2016-06-05T02:03:59.954555+00:00 app[scheduler.4949]:   File "/app/.conda/lib/python3.5/site-packages/conda_smithy/lint_recipe.py", line 19, in __getattr__
2016-06-05T02:03:59.954556+00:00 app[scheduler.4949]:     return unicode('{}.{}'.format(self, name))
2016-06-05T02:03:59.954556+00:00 app[scheduler.4949]: NameError: name 'unicode' is not defined
```

Looks like I need to get some fixes from conda-smithy onto the heroku worker.

**Comment by jakirkham** [comment]
So, I think we have generated a PR and/or merged one that is sufficiently updated for all repos except one. It appears `erlang` has not seen a new re-rendering PR for `master`. Any idea why that might be?

**Comment by pelson** [comment]
No idea. I have just created one though: https://github.com/conda-forge/erlang-feedstock/pull/11/files.

**Comment by jakirkham** [comment]
Thanks for doing that.

**Comment by jakirkham** [comment]
Now that I have cleared a bunch of these out I see that `icu` doesn't have one, but I think that is it. Though I may just do that manually.

**Comment by jakirkham** [comment]
Re-rendering `icu` with this manually generated PR ( https://github.com/conda-forge/icu-feedstock/pull/7 ).

**Comment by pelson** [comment]
FWIW rerendering takes place at https://github.com/conda-forge/conda-forge-maintenance.

I have just re-enabled MNT rerendering as per https://github.com/conda-forge/conda-forge-maintenance/issues/4.

**Comment by jakirkham** [comment]
> FWIW rerendering takes place at https://github.com/conda-forge/conda-forge-maintenance.

Oops. 😳 Noted.

> I have just re-enabled MNT rerendering as per conda-forge/conda-forge-maintenance#4.

🎉 🎉 🎉
