### ISSUE TITLE
weird cascading error

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-webservices#365]
certain errors in the CFEP-13 endpoints produce a cascade of errors like this

```
ERROR:tornado.application:Uncaught exception POST /feedstock-outputs/copy (147.75.105.54)
2020-04-23T04:13:11.062357+00:00 app[web.1]: HTTPServerRequest(protocol='https', host='conda-forge.herokuapp.com', method='POST', uri='/feedstock-outputs/copy', version='HTTP/1.1', remote_ip='147.75.105.54')
2020-04-23T04:13:11.062358+00:00 app[web.1]: Traceback (most recent call last):
2020-04-23T04:13:11.062358+00:00 app[web.1]:   File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
2020-04-23T04:13:11.062359+00:00 app[web.1]:     result = await result
2020-04-23T04:13:11.062359+00:00 app[web.1]:   File "/conda_forge_webservices/conda_forge_webservices/webapp.py", line 505, in post
2020-04-23T04:13:11.062360+00:00 app[web.1]:     print("\n===================================================")
2020-04-23T04:13:11.062360+00:00 app[web.1]: ValueError: I/O operation on closed file.
2020-04-23T04:13:11.062859+00:00 app[web.1]: ERROR:tornado.access:500 POST /feedstock-outputs/copy (147.75.105.54) 1.12ms
2020-04-23T04:14:19.345611+00:00 heroku[router]: at=info method=POST path="/feedstock-outputs/validate" host=conda-forge.herokuapp.com request_id=6773a0d9-2186-464f-8c9f-3e7afb519b4d fwd="162.221.90.123" dyno=web.1 connect=1ms service=4ms status=500 bytes=276 protocol=https
2020-04-23T04:14:19.344610+00:00 app[web.1]: ERROR:tornado.application:Uncaught exception POST /feedstock-outputs/validate (162.221.90.123)
2020-04-23T04:14:19.344620+00:00 app[web.1]: HTTPServerRequest(protocol='https', host='conda-forge.herokuapp.com', method='POST', uri='/feedstock-outputs/validate', version='HTTP/1.1', remote_ip='162.221.90.123')
2020-04-23T04:14:19.344621+00:00 app[web.1]: Traceback (most recent call last):
2020-04-23T04:14:19.344622+00:00 app[web.1]:   File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
2020-04-23T04:14:19.344622+00:00 app[web.1]:     result = await result
2020-04-23T04:14:19.344625+00:00 app[web.1]:   File "/conda_forge_webservices/conda_forge_webservices/webapp.py", line 463, in post
2020-04-23T04:14:19.344626+00:00 app[web.1]:     print("\n===================================================")
2020-04-23T04:14:19.344627+00:00 app[web.1]: ValueError: I/O operation on closed file.
2020-04-23T04:14:19.345323+00:00 app[web.1]: ERROR:tornado.access:500 POST /feedstock-outputs/validate (162.221.90.123) 1.94ms
2020-04-23T04:15:56.169043+00:00 heroku[router]: at=info method=POST path="/feedstock-outputs/copy" host=conda-forge.herokuapp.com request_id=b7b4bddb-3333-4e47-a89f-66f7b750e221 fwd="147.75.105.54" dyno=web.1 connect=1ms service=3ms status=500 bytes=276 protocol=https
2020-04-23T04:15:56.168474+00:00 app[web.1]: ERROR:tornado.application:Uncaught exception POST /feedstock-outputs/copy (147.75.105.54)
2020-04-23T04:15:56.168492+00:00 app[web.1]: HTTPServerRequest(protocol='https', host='conda-forge.herokuapp.com', method='POST', uri='/feedstock-outputs/copy', version='HTTP/1.1', remote_ip='147.75.105.54')
2020-04-23T04:15:56.168493+00:00 app[web.1]: Traceback (most recent call last):
2020-04-23T04:15:56.168494+00:00 app[web.1]:   File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
2020-04-23T04:15:56.168495+00:00 app[web.1]:     result = await result
2020-04-23T04:15:56.168495+00:00 app[web.1]:   File "/conda_forge_webservices/conda_forge_webservices/webapp.py", line 505, in post
2020-04-23T04:15:56.168496+00:00 app[web.1]:     print("\n===================================================")
2020-04-23T04:15:56.168497+00:00 app[web.1]: ValueError: I/O operation on closed file.
2020-04-23T04:15:56.169063+00:00 app[web.1]: ERROR:tornado.access:500 POST /feedstock-outputs/copy (147.75.105.54) 1.61ms
2020-04-23T04:17:36.321957+00:00 heroku[router]: at=info method=POST path="/feedstock-outputs/validate" host=conda-forge.herokuapp.com request_id=35f8e095-f0fc-44ff-ba7a-cf869d14139a fwd="38.39.178.136" dyno=web.1 connect=1ms service=3ms status=500 bytes=276 protocol=https
2020-04-23T04:17:36.313378+00:00 app[web.1]: ERROR:tornado.application:Uncaught exception POST /feedstock-outputs/validate (38.39.178.136)
2020-04-23T04:17:36.313395+00:00 app[web.1]: HTTPServerRequest(protocol='https', host='conda-forge.herokuapp.com', method='POST', uri='/feedstock-outputs/validate', version='HTTP/1.1', remote_ip='38.39.178.136')
2020-04-23T04:17:36.313396+00:00 app[web.1]: Traceback (most recent call last):
2020-04-23T04:17:36.313396+00:00 app[web.1]:   File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
2020-04-23T04:17:36.313397+00:00 app[web.1]:     result = await result
2020-04-23T04:17:36.313397+00:00 app[web.1]:   File "/conda_forge_webservices/conda_forge_webservices/webapp.py", line 463, in post
2020-04-23T04:17:36.313398+00:00 app[web.1]:     print("\n===================================================")
2020-04-23T04:17:36.313399+00:00 app[web.1]: ValueError: I/O operation on closed file.
2020-04-23T04:17:36.313863+00:00 app[web.1]: ERROR:tornado.access:500 POST /feedstock-outputs/validate (38.39.178.136) 1.73ms
2020-04-23T04:18:46.233488+00:00 heroku[router]: at=info method=POST path="/feedstock-outputs/copy" host=conda-forge.herokuapp.com request_id=9dbfb86e-8459-41a3-b12a-3fe45070ad35 fwd="147.75.105.54" dyno=web.1 connect=0ms service=3ms status=500 bytes=276 protocol=https
2020-04-23T04:18:46.232527+00:00 app[web.1]: ERROR:tornado.application:Uncaught exception POST /feedstock-outputs/copy (147.75.105.54)
2020-04-23T04:18:46.232538+00:00 app[web.1]: HTTPServerRequest(protocol='https', host='conda-forge.herokuapp.com', method='POST', uri='/feedstock-outputs/copy', version='HTTP/1.1', remote_ip='147.75.105.54')
2020-04-23T04:18:46.232539+00:00 app[web.1]: Traceback (most recent call last):
2020-04-23T04:18:46.232540+00:00 app[web.1]:   File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
2020-04-23T04:18:46.232541+00:00 app[web.1]:     result = await result
2020-04-23T04:18:46.232541+00:00 app[web.1]:   File "/conda_forge_webservices/conda_forge_webservices/webapp.py", line 505, in post
2020-04-23T04:18:46.232542+00:00 app[web.1]:     print("\n===================================================")
2020-04-23T04:18:46.232543+00:00 app[web.1]: ValueError: I/O operation on closed file.
2020-04-23T04:18:46.233189+00:00 app[web.1]: ERROR:tornado.access:500 POST /feedstock-outputs/copy (147.75.105.54) 1.58ms
2020-04-23T04:20:58.385841+00:00 heroku[router]: at=info method=POST path="/feedstock-outputs/validate" host=conda-forge.herokuapp.com request_id=74b27301-3dd4-4c53-9c96-feeaace9d684 fwd="38.39.178.178" dyno=web.1 connect=0ms service=2ms status=500 bytes=276 protocol=https
2020-04-23T04:20:58.385758+00:00 app[web.1]: ERROR:tornado.application:Uncaught exception POST /feedstock-outputs/validate (38.39.178.178)
2020-04-23T04:20:58.385772+00:00 app[web.1]: HTTPServerRequest(protocol='https', host='conda-forge.herokuapp.com', method='POST', uri='/feedstock-outputs/validate', version='HTTP/1.1', remote_ip='38.39.178.178')
2020-04-23T04:20:58.385773+00:00 app[web.1]: Traceback (most recent call last):
2020-04-23T04:20:58.385774+00:00 app[web.1]:   File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
2020-04-23T04:20:58.385775+00:00 app[web.1]:     result = await result
2020-04-23T04:20:58.385776+00:00 app[web.1]:   File "/conda_forge_webservices/conda_forge_webservices/webapp.py", line 463, in post
2020-04-23T04:20:58.385776+00:00 app[web.1]:     print("\n===================================================")
2020-04-23T04:20:58.385777+00:00 app[web.1]: ValueError: I/O operation on closed file.
2020-04-23T04:20:58.386246+00:00 app[web.1]: ERROR:tornado.access:500 POST /feedstock-outputs/validate (38.39.178.178) 1.21ms
```

**Comment by beckermr** [comment]
Using logging instead of print seems to have fixed this. IDK why but let's forge ahead.

**Comment by beckermr** [comment]
This is probably the use of redirect_stderr, redirect_stdout in smithy.
