### ISSUE TITLE
Linter failing

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge-webservices#43]
Is this a transient issue?

```
HTTPServerRequest(protocol='http', host='conda-forge.herokuapp.com', method='POST', uri='/conda-linting/hook', version='HTTP/1.1', headers={'X-Github-Event': 'pull_request', 'Total-Route-Time': '0', 'Accept': '*/*', : 'http', ...})
2016-08-24T08:16:24.761335+00:00 app[web.1]: Traceback (most recent call last):
2016-08-24T08:16:24.761340+00:00 app[web.1]:     issue = repo.get_issue(pr_id)
2016-08-24T08:16:24.761339+00:00 app[web.1]:   File "/app/conda_forge_webservices/linting.py", line 27, in compute_lint_message
2016-08-24T08:16:24.761338+00:00 app[web.1]:   File "/app/conda_forge_webservices/webapp.py", line 78, in post
2016-08-24T08:16:24.761340+00:00 app[web.1]:   File "/app/.conda/lib/python3.5/site-packages/github/Repository.py", line 1599, in get_issue
2016-08-24T08:16:24.761340+00:00 app[web.1]:     self.url + "/issues/" + str(number)
2016-08-24T08:16:24.761339+00:00 app[web.1]:     lint_info = linting.compute_lint_message(owner, repo_name, pr_id)
2016-08-24T08:16:24.761341+00:00 app[web.1]:   File "/app/.conda/lib/python3.5/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
2016-08-24T08:16:24.761792+00:00 app[web.1]: ERROR:tornado.access:500 POST /conda-linting/hook (192.30.252.45) 184.69ms
2016-08-24T08:16:24.761343+00:00 app[web.1]: github.GithubException.UnknownObjectException: 404 {'documentation_url': 'https://developer.github.com/v3', 'message': 'Not Found'}
2016-08-24T08:16:24.761342+00:00 app[web.1]:     return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
2016-08-24T08:16:24.761342+00:00 app[web.1]:   File "/app/.conda/lib/python3.5/site-packages/github/Requester.py", line 180, in __check
2016-08-24T08:16:24.761342+00:00 app[web.1]:     raise self.__createException(status, responseHeaders, output)
```

Is this the reason for https://github.com/conda-forge/bob.io.image-feedstock/pull/17#issuecomment-241990912?

**Comment by jakirkham** [comment]
Looks the same as issue ( https://github.com/conda-forge/conda-forge-webservices/issues/30 ).
