### ISSUE TITLE
Failure to Create Re-rendering PR

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-webservices#78]
Appears that in some cases the re-rendering PR cannot be created and so the re-rendering service just crashes. If failing to create a PR is acceptable in these circumstances, we should handle it better. If not, we should fix how we create PRs. Example below. In this case, it seems a re-rendering PR would be needed.

```
2016-10-10T02:16:46.520952+00:00 app[rerender.1]: Fetching  cf_units
2016-10-10T02:16:46.520965+00:00 app[rerender.1]: Checking cf_units-feedstock
2016-10-10T02:16:48.994418+00:00 app[rerender.1]: Fetching package metadata .........
2016-10-10T02:16:52.747445+00:00 app[rerender.1]: Fetching package metadata .........
2016-10-10T02:16:56.953141+00:00 app[rerender.1]: Fetching package metadata .........
2016-10-10T02:17:00.901689+00:00 app[rerender.1]: Fetching package metadata .........
2016-10-10T02:17:04.054861+00:00 app[rerender.1]: Fetching package metadata .........
2016-10-10T02:17:07.040194+00:00 app[rerender.1]: Using Anaconda API: https://api.anaconda.org
2016-10-10T02:17:07.052282+00:00 app[rerender.1]: Traceback (most recent call last):
2016-10-10T02:17:07.052284+00:00 app[rerender.1]:   File "/tmp/conda-execute_xxx", line 268, in <module>
2016-10-10T02:17:07.052285+00:00 app[rerender.1]:     conda_smithy.configure_feedstock.main(feedstock.directory)
2016-10-10T02:17:07.052287+00:00 app[rerender.1]:   File "/app/.conda/tmp_envs/xxx/lib/python3.5/contextlib.py", line 66, in __exit__
2016-10-10T02:17:07.052288+00:00 app[rerender.1]:     next(self.gen)
2016-10-10T02:17:07.052289+00:00 app[rerender.1]:   File "/tmp/conda-execute_xxx", line 219, in create_update_pr
2016-10-10T02:17:07.052289+00:00 app[rerender.1]:     head="conda-forge-admin:{}".format(target_branch), base=remote_head)
2016-10-10T02:17:07.052290+00:00 app[rerender.1]:   File "/app/.conda/tmp_envs/xxx/lib/python3.5/site-packages/github/Repository.py", line 976, in create_pull
2016-10-10T02:17:07.052291+00:00 app[rerender.1]:     return self.__create_pull_1(*args, **kwds)
2016-10-10T02:17:07.052292+00:00 app[rerender.1]:   File "/app/.conda/tmp_envs/xxx/lib/python3.5/site-packages/github/Repository.py", line 985, in __create_pull_1
2016-10-10T02:17:07.052293+00:00 app[rerender.1]:     return self.__create_pull(title=title, body=body, base=base, head=head)
2016-10-10T02:17:07.052293+00:00 app[rerender.1]:   File "/app/.conda/tmp_envs/xxx/lib/python3.5/site-packages/github/Repository.py", line 998, in __create_pull
2016-10-10T02:17:07.052294+00:00 app[rerender.1]:     input=post_parameters
2016-10-10T02:17:07.052296+00:00 app[rerender.1]:     return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
2016-10-10T02:17:07.052296+00:00 app[rerender.1]:   File "/app/.conda/tmp_envs/xxx/lib/python3.5/site-packages/github/Requester.py", line 180, in __check
2016-10-10T02:17:07.052295+00:00 app[rerender.1]:   File "/app/.conda/tmp_envs/xxx/lib/python3.5/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
2016-10-10T02:17:07.052297+00:00 app[rerender.1]:     raise self.__createException(status, responseHeaders, output)
2016-10-10T02:17:07.052298+00:00 app[rerender.1]: github.GithubException.GithubException: 422 {'documentation_url': 'https://developer.github.com/v3/pulls/#create-a-pull-request', 'message': 'Validation Failed', 'errors': [{'message': 'No commits between conda-forge:master and conda-forge-admin:feedstock_rerender_master', 'code': 'custom', 'resource': 'PullRequest'}]}
2016-10-10T02:17:07.703712+00:00 app[rerender.1]: CalledProcessError: Command '['python', '/tmp/conda-execute_xxx', '--feedstocks-dir', 'feedstocks', '--limit', '5']' returned non-zero exit status 1
2016-10-10T02:17:09.928541+00:00 heroku[rerender.1]: State changed from crashed to starting
2016-10-10T02:17:09.927528+00:00 heroku[rerender.1]: State changed from up to crashed
2016-10-10T02:17:09.915179+00:00 heroku[rerender.1]: Process exited with status 1
```

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/conda-forge-maintenance #47](https://github.com/conda-forge/conda-forge-maintenance/issues/47) via [**ZenHub**](https://www.zenhub.com/)
